### ISSUE TITLE
Cannot read property 'apply' of undefined. Ember 1.13.x

### ISSUE THREAD

**Issue by daniel-de-wit** [binhums/ember-cli-bugsnag#60]
For some reason Ember 1.13.x doesn't have `treeForApp` available on `this._super` on line 23:36

ember-cli-bugsnag/index.js:

``` js
  ...

  treeForApp: function() {
    if (this._includeBugsnag) {
      return this._super.treeForApp.apply(this, arguments); // Cannot read property 'apply' of undefined
    }
  },

  ...
```

Seems the ember-data team discovered this also: https://github.com/emberjs/data/blob/master/index.js#L95

Currently installed ember-cli-bugsnag v1.0.2.

Is there any way to fix this?

**Comment by binhums** [comment]
Hi @daniel-de-wit thanks for raising. I really like that TODO in the ember-data codebase.

I'm a bit surprised that this is happening for 1.13.x because we run against that version with Ember Try. At the very least our tests should fail for this problem.

https://30-31278646-gh.circle-artifacts.com/0/tmp/circle-junit.r7QxMFj/testem-ember-1.13.xml

I was not able to reproduce this using ember try with 1.13.0. At least using the dummy app I was able to produce an issue that published to bugsnag.

Have you had any progress here? If you can push up a repo which reproduces the issue that would be massively helpful.

**Comment by binhums** [comment]
Also worth noting that I'm testing it from the addon dummy app. I'm not testing an integration. That is probably the problem here. I'll see if I can expand on my testing if I don't hear from you.

Also of course, if you find a fix please do open a pull request.

**Comment by binhums** [comment]
Assuming we can close this. @daniel-de-wit if this still a problem for you I will reopen the issue.
